### ISSUE TITLE
Close function doesn't remove full youtube ...

### ISSUE THREAD

**Issue by gr1298** [Bikossor/ALightBox#1]
Hi, should be used:
 $('#alb_overlay').fadeOut(settings.effectTime, function(){$(this).remove();});
instead of 
$('#alb_overlay').fadeOut(settings.effectTime); 
already in use?
I asked that because i didn't have my youtube object full removed as the overlay window get closed but I still have the sound continuing....

**Comment by Bikossor** [comment]
I'll check that out! Thanks for the note :D

**Comment by Bikossor** [comment]
I can't really recreate this problem, but I saw that the source files are not correct either.. I fixed up the source code. Maybe you can try this again 😃

**Comment by gr1298** [comment]
Hi, to reproduce my problem: after you open your youtube lightbox, just click on play button and let it start, so as you here a song  just click in the "X" to close the lightbox window and I am getting it the lightbox window closed but the audio still there and if you reopen the lightbox window well the audio disappear.... but if you use a new youtube window well you have the same problem keeping going, well I tried remove and didn't work properly so i tried empty but it doesn't let me reopen completely, so is up to you

**Comment by Bikossor** [comment]
I just testet it on Google Chrome and it behaved the way you described it. I'll take care of this problem. Did you use Chrome as well?

**Comment by gr1298** [comment]
Yes on chrome and also on Edge

**Comment by Bikossor** [comment]
Okay **NOW** it's fixed. I also had to change some other parts from ES6 to ES5 because the IE isn't really compatible with it...

**Comment by Bikossor** [comment]
Does it work for you now?
