### ISSUE TITLE
Always the first element is opened when clicking on nested elements

### ISSUE THREAD

**Issue by dominibase** [Bikossor/ALightBox#41]
Hi, 
I am using your amazing ALightBox script version Photron-0.2.0
I have a problem using it with the scroll swiper script https://swiperjs.com/
here is my example:
			      <div class="t" data-title="landscape">
                              <div class="swiper mySwiper2" >
                              <div class="swiper-wrapper" >
              
                              <div class="swiper-slide" >
                              <a class="alb-item" href="https://www.youtube.com/watch?v=6FRS4MF7UvQ" ></a>
                              </div>

                              <div class="swiper-slide" >
                              <a class="alb-item" href="https://www.youtube.com/watch?v=9SJc7N0S41A" ></a>
                              </div> 

                              <div class="swiper-slide" >
                              <a class="alb-item" href="https://www.youtube.com/watch?v=9SJc7N0S41A" ></a>
                              </div> 

			      <div class="swiper-slide">
                              <a class="alb-item" href="https://www.youtube.com/watch?v=-7RlEe_FGSA" ></a>
                              </div> 
                                        
                              </div>
                                        <div class="swiper-button-next"></div>
                                        <div class="swiper-button-prev"></div>

                              </div>
                              </div>

When I click on the 3 or 4 videos on the scroll it always opens the first video, it does not recognize the clicked video, very likely there is a conflict because I insert <div class = "swiper-slide"> </div> with each video, in fact eliminating this piece of code works.
I would like to use your script because I am in love with it, how can I solve?
thank you

**Comment by Bikossor** [comment]
@dominibase I'm looking into it :)

**Comment by Bikossor** [comment]
> @dominibase there is a conflict because I insert

What are you inserting? Because there is no code snipped 😄

**Comment by dominibase** [comment]
<head>
<link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
<link rel="stylesheet" href="assets/css/ALightBox-0.2.0.css">
 <style media="screen">
    .t img {
      width: 100%;
      height: auto;
    }
  </style>
</head>
<body>
<div class="t" data-title="myvideo">
                            <div class="swiper mySwiper2">
                            <div class="swiper-wrapper" >                                  
		            <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=6FRS4MF7UvQ" ></a>
                          </div>

                          <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=9SJc7N0S41A" ></a>
                          </div> 

                          <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=9SJc7N0S41A" ></a>
                          </div> 

		          <div class="swiper-slide">
                          <a class="alb-item" href="https://www.youtube.com/watch?v=-7RlEe_FGSA" ></a>
                          </div> 
                                    
                          </div>
                                    <div class="swiper-button-next"></div>
                                    <div class="swiper-button-prev"></div>

                          </div>
                          </div>
  <script>
            var swiper = new Swiper(".mySwiper2", {
              slidesPerView: 1,
              spaceBetween: 5,
              navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
      },
              autoplay: {
        delay: 2000,
        disableOnInteraction: false,
        },
        breakpoints: {
        640: {
          slidesPerView: 2,
          spaceBetween: 2,
        },
        768: {
          slidesPerView: 3,
          spaceBetween: 4,
        },
        1024: {
          slidesPerView: 4,
          spaceBetween: 5,
        },
  }
            });
          
          </script>
       <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>         
       <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
       <script src="assets/js/ALightBox-0.2.0.js"></script>
       <script type="text/javascript">
			$('.swiper-wrapper').ALightBox({
				showYoutubeThumbnails: true
			});
       </script>
       
</body>

**Comment by dominibase** [comment]
`<head>
<link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
<link rel="stylesheet" href="assets/css/ALightBox-0.2.0.css">
 <style media="screen">
    .t img {
      width: 100%;
      height: auto;
    }
  </style>
</head>
<body>
<div class="t" data-title="myvideo">
                            <div class="swiper mySwiper2">
                            <div class="swiper-wrapper" >                                  
		            <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=6FRS4MF7UvQ" ></a>
                          </div>

                          <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=9SJc7N0S41A" ></a>
                          </div> 

                          <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=9SJc7N0S41A" ></a>
                          </div> 

		          <div class="swiper-slide">
                          <a class="alb-item" href="https://www.youtube.com/watch?v=-7RlEe_FGSA" ></a>
                          </div> 
                                    
                          </div>
                                    <div class="swiper-button-next"></div>
                                    <div class="swiper-button-prev"></div>

                          </div>
                          </div>
  <script>
            var swiper = new Swiper(".mySwiper2", {
              slidesPerView: 1,
              spaceBetween: 5,
              navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
      },
              autoplay: {
        delay: 2000,
        disableOnInteraction: false,
        },
        breakpoints: {
        640: {
          slidesPerView: 2,
          spaceBetween: 2,
        },
        768: {
          slidesPerView: 3,
          spaceBetween: 4,
        },
        1024: {
          slidesPerView: 4,
          spaceBetween: 5,
        },
  }
            });
          
          </script>
       <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>         
       <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
       <script src="assets/js/ALightBox-0.2.0.js"></script>
       <script type="text/javascript">
			$('.swiper-wrapper').ALightBox({
				showYoutubeThumbnails: true
			});
       </script>
       
</body>`

**Comment by dominibase** [comment]
`<head>
<link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
<link rel="stylesheet" href="assets/css/ALightBox-0.2.0.css">
 <style media="screen">
    .t img {
      width: 100%;
      height: auto;
    }
  </style>
</head>
<body>
<div class="t" data-title="myvideo">
                            <div class="swiper mySwiper2">
                            <div class="swiper-wrapper" >                                  
		            <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=6FRS4MF7UvQ" ></a>
                          </div>

                          <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=9SJc7N0S41A" ></a>
                          </div> 

                          <div class="swiper-slide" >
                          <a class="alb-item" href="https://www.youtube.com/watch?v=9SJc7N0S41A" ></a>
                          </div> 

		          <div class="swiper-slide">
                          <a class="alb-item" href="https://www.youtube.com/watch?v=-7RlEe_FGSA" ></a>
                          </div> 
                                    
                          </div>
                                    <div class="swiper-button-next"></div>
                                    <div class="swiper-button-prev"></div>

                          </div>
                          </div>
  <script>
            var swiper = new Swiper(".mySwiper2", {
              slidesPerView: 1,
              spaceBetween: 5,
              navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
      },
              autoplay: {
        delay: 2000,
        disableOnInteraction: false,
        },
        breakpoints: {
        640: {
          slidesPerView: 2,
          spaceBetween: 2,
        },
        768: {
          slidesPerView: 3,
          spaceBetween: 4,
        },
        1024: {
          slidesPerView: 4,
          spaceBetween: 5,
        },
  }
            });
          
          </script>
       <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>         
       <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
       <script src="assets/js/ALightBox-0.2.0.js"></script>
       <script type="text/javascript">
			$('.swiper-wrapper').ALightBox({
				showYoutubeThumbnails: true
			});
       </script>
       
</body>`

**Comment by dominibase** [comment]
i can't copy all html code here

**Comment by dominibase** [comment]
[
[code.txt](https://github.com/Bikossor/Photron/files/8500197/code.txt)
](url)

**Comment by Bikossor** [comment]
I found the problem and I'm gonna fix this now 😄 

Edit for more context: the lightbox has a problem with the HTML structure since the `.alb-item`s are not **direct** children of your `.swiper-wrapper` (because they are nested). I'll fix this so the lightbox has no problem with the nesting anymore 😄

**Comment by Bikossor** [comment]
@dominibase it's fixed in the release [0.2.2](https://github.com/Bikossor/Photron/releases/tag/0.2.2).
